BEGIN;

ALTER TABLE IF EXISTS core.backtest_run_summary
  ADD COLUMN IF NOT EXISTS gross_total_return DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS gross_annualized_return DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS total_commission DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS total_slippage_cost DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS total_transaction_cost DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS cost_drag_bps DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS avg_gross_exposure DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS avg_net_exposure DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS sortino_ratio DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS calmar_ratio DOUBLE PRECISION;

COMMIT;
