location: East US
name: backtests-job
type: Microsoft.App/jobs
tags:
  owner: ${RESOURCE_TAG_OWNER}
  cost-center: ${RESOURCE_TAG_COST_CENTER}
  workload: ${RESOURCE_TAG_WORKLOAD}
  environment: ${RESOURCE_TAG_ENVIRONMENT}
identity:
  type: UserAssigned
  userAssignedIdentities:
    "${ACR_PULL_IDENTITY_RESOURCE_ID}": {}
properties:
  configuration:
    triggerType: Manual
    manualTriggerConfig:
      parallelism: 1
      replicaCompletionCount: 1
    replicaRetryLimit: 1
    replicaTimeout: 14400
    registries:
    - server: assetallocationacr.azurecr.io
      identity: "${ACR_PULL_IDENTITY_RESOURCE_ID}"
    secrets:
    - name: azure-storage-connection-string
      value: ${AZURE_STORAGE_CONNECTION_STRING}
    - name: pg-dsn
      value: ${POSTGRES_DSN}
  environmentId: ${CONTAINER_APPS_ENVIRONMENT_ID}
  template:
    serviceAccountName: ${SERVICE_ACCOUNT_NAME}
    containers:
    - env:
      - name: LOG_FORMAT
        value: JSON
      - name: LOG_LEVEL
        value: INFO
      - name: DISABLE_DOTENV
        value: "true"
      - name: AZURE_CLIENT_ID
        value: ${ACR_PULL_IDENTITY_CLIENT_ID}
      - name: AZURE_STORAGE_ACCOUNT_NAME
        value: ${AZURE_STORAGE_ACCOUNT_NAME}
      - name: AZURE_STORAGE_CONNECTION_STRING
        secretRef: azure-storage-connection-string
      - name: AZURE_CONTAINER_COMMON
        value: ${AZURE_CONTAINER_COMMON}
      - name: POSTGRES_DSN
        secretRef: pg-dsn
      image: ${JOB_IMAGE}
      imageType: ContainerImage
      name: backtests-job
      command: ["python", "-m", "tasks.backtesting.worker"]
      resources:
        cpu: 2.0
        memory: 4Gi
  workloadProfileName: Consumption
