location: East US
name: platinum-rankings-job
type: Microsoft.App/jobs
tags:
  owner: ${RESOURCE_TAG_OWNER}
  cost-center: ${RESOURCE_TAG_COST_CENTER}
  workload: ${RESOURCE_TAG_WORKLOAD}
  environment: ${RESOURCE_TAG_ENVIRONMENT}
identity:
  type: UserAssigned
  userAssignedIdentities:
    "${ACR_PULL_IDENTITY_RESOURCE_ID}": {}
properties:
  configuration:
    triggerType: Manual
    manualTriggerConfig:
      parallelism: 1
      replicaCompletionCount: 1
    replicaRetryLimit: 1
    replicaTimeout: 14400
    registries:
    - server: assetallocationacr.azurecr.io
      identity: "${ACR_PULL_IDENTITY_RESOURCE_ID}"
    secrets:
    - name: pg-dsn
      value: ${POSTGRES_DSN}
  environmentId: ${CONTAINER_APPS_ENVIRONMENT_ID}
  template:
    serviceAccountName: ${SERVICE_ACCOUNT_NAME}
    containers:
    - env:
      - name: LOG_FORMAT
        value: JSON
      - name: LOG_LEVEL
        value: INFO
      - name: DISABLE_DOTENV
        value: "true"
      - name: AZURE_CLIENT_ID
        value: ${ACR_PULL_IDENTITY_CLIENT_ID}
      - name: POSTGRES_DSN
        secretRef: pg-dsn
      - name: RANKING_STRATEGY_NAME
        value: ${RANKING_STRATEGY_NAME}
      - name: RANKING_START_DATE
        value: ${RANKING_START_DATE}
      - name: RANKING_END_DATE
        value: ${RANKING_END_DATE}
      image: ${JOB_IMAGE}
      imageType: ContainerImage
      name: platinum-rankings-job
      command: ["python", "-m", "tasks.ranking.platinum_rankings"]
      resources:
        cpu: 1.5
        memory: 3Gi
  workloadProfileName: Consumption
