from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import sys

import yaml


GENERATED_MARKER = "<!-- Generated by scripts/sync_github_copilot_agents.py. Edit the source skill instead. -->"


@dataclass(frozen=True)
class SkillMetadata:
    name: str
    description: str
    display_name: str
    skill_path: Path
    references_path: Path | None
    openai_agent_path: Path | None


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_skill_frontmatter(text: str) -> dict[str, str]:
    match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, re.DOTALL)
    if not match:
        raise ValueError("SKILL.md is missing YAML frontmatter")
    data = yaml.safe_load(match.group(1))
    if not isinstance(data, dict):
        raise ValueError("SKILL.md frontmatter must parse to a mapping")
    return {str(key): str(value) for key, value in data.items()}


def first_heading(text: str) -> str | None:
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else None


def read_display_name(skill_dir: Path, skill_text: str) -> str:
    openai_path = skill_dir / "agents" / "openai.yaml"
    if openai_path.exists():
        openai_text = openai_path.read_text(encoding="utf-8")
        match = re.search(r'^\s*display_name:\s*"?(.*?)"?\s*$', openai_text, re.MULTILINE)
        if match and match.group(1).strip():
            return match.group(1).strip()
        try:
            parsed = yaml.safe_load(openai_text) or {}
        except yaml.YAMLError:
            parsed = {}
        interface = parsed.get("interface", {})
        if isinstance(interface, dict):
            display_name = interface.get("display_name")
            if isinstance(display_name, str) and display_name.strip():
                return display_name.strip()
    heading = first_heading(skill_text)
    if heading:
        return heading
    return skill_dir.name.replace("-", " ").title()


def iter_skills(root: Path) -> list[SkillMetadata]:
    skills_dir = root / ".codex" / "skills"
    metadata: list[SkillMetadata] = []
    for skill_dir in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
        skill_path = skill_dir / "SKILL.md"
        if not skill_path.exists():
            continue
        skill_text = skill_path.read_text(encoding="utf-8")
        frontmatter = parse_skill_frontmatter(skill_text)
        metadata.append(
            SkillMetadata(
                name=skill_dir.name,
                description=frontmatter["description"].strip(),
                display_name=read_display_name(skill_dir, skill_text),
                skill_path=skill_path,
                references_path=(skill_dir / "references" / "agent.md") if (skill_dir / "references" / "agent.md").exists() else None,
                openai_agent_path=(skill_dir / "agents" / "openai.yaml") if (skill_dir / "agents" / "openai.yaml").exists() else None,
            )
        )
    return metadata


def relative_path(path: Path, start: Path) -> str:
    return path.relative_to(start).as_posix()


def build_body(metadata: SkillMetadata, root: Path) -> str:
    lines = [
        GENERATED_MARKER,
        "",
        f"You are {metadata.display_name}, the GitHub Copilot counterpart to the repo-local Codex skill `{metadata.name}`.",
        "",
        "## Mission",
        "",
        metadata.description,
        "",
        "## Source Of Truth",
        "",
        "Start every task by reading these repo-local skill files:",
        "",
        f"- `{relative_path(metadata.skill_path, root)}`",
    ]
    if metadata.references_path is not None:
        lines.append(f"- `{relative_path(metadata.references_path, root)}`")
    if metadata.openai_agent_path is not None:
        lines.append(f"- `{relative_path(metadata.openai_agent_path, root)}`")
    lines.extend(
        [
            "",
            "Use them as the canonical instructions for workflow, output format, scripts, assets, guardrails, and stop conditions.",
            "",
            "## Operating Rules",
            "",
            f"- Follow the repository `AGENTS.md` and keep `.codex/skills/{metadata.name}/` authoritative.",
            f"- Reuse scripts, templates, references, and assets under `.codex/skills/{metadata.name}/` instead of recreating them.",
            "- Gather evidence from repo files, diffs, tests, logs, and tool output before making claims.",
            "- Make the smallest safe change that satisfies the current task.",
            "- If the skill defines a strict report or artifact format, follow it exactly.",
            "- Ask targeted questions only when missing context materially changes the outcome; otherwise proceed with explicit assumptions.",
            "",
            "## Task Start Checklist",
            "",
            "1. Read the source files above.",
            "2. Identify the workflow or mode the request maps to.",
            "3. Confirm the required artifacts, constraints, and validation steps.",
            "4. Execute the skill using the least risky tool path that still finishes the job.",
            "",
        ]
    )
    return "\n".join(lines)


def render_agent(metadata: SkillMetadata, root: Path) -> str:
    frontmatter = yaml.safe_dump(
        {
            "name": metadata.name,
            "description": metadata.description,
            "target": "github-copilot",
            "tools": ["read", "search", "edit", "execute"],
        },
        sort_keys=False,
        allow_unicode=False,
    ).strip()
    return f"---\n{frontmatter}\n---\n\n{build_body(metadata, root)}"


def write_agents(root: Path, overwrite_existing: bool) -> tuple[list[str], list[str]]:
    agents_dir = root / ".github" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    created_or_updated: list[str] = []
    skipped: list[str] = []

    for metadata in iter_skills(root):
        destination = agents_dir / f"{metadata.name}.agent.md"
        if destination.exists():
            existing_text = destination.read_text(encoding="utf-8")
            if not overwrite_existing and GENERATED_MARKER not in existing_text:
                skipped.append(metadata.name)
                continue
        destination.write_text(render_agent(metadata, root), encoding="utf-8")
        created_or_updated.append(metadata.name)

    return created_or_updated, skipped


def check_coverage(root: Path) -> list[str]:
    missing: list[str] = []
    for metadata in iter_skills(root):
        destination = root / ".github" / "agents" / f"{metadata.name}.agent.md"
        if not destination.exists():
            missing.append(metadata.name)
    return missing


def main() -> int:
    parser = argparse.ArgumentParser(description="Create GitHub Copilot agent wrappers for repo-local Codex skills.")
    parser.add_argument("--check", action="store_true", help="Fail if any skill is missing a matching .github/agents file.")
    parser.add_argument(
        "--overwrite-existing",
        action="store_true",
        help="Overwrite existing .github/agents files, including hand-authored ones.",
    )
    args = parser.parse_args()

    root = repo_root()
    if args.check:
        missing = check_coverage(root)
        if missing:
            print("Missing GitHub Copilot agents:", ", ".join(missing))
            return 1
        print("All repo-local Codex skills have matching GitHub Copilot agent files.")
        return 0

    written, skipped = write_agents(root, overwrite_existing=args.overwrite_existing)
    print(f"Wrote {len(written)} GitHub Copilot agent files.")
    if written:
        print("Updated:", ", ".join(written))
    if skipped:
        print("Skipped existing hand-authored files:", ", ".join(skipped))
    return 0


if __name__ == "__main__":
    sys.exit(main())
